spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show-sql: true
        format_sql: true

    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
